### PR TITLE
JavaScript. Homework 7 (Reduce and Map methods)

### PR DESCRIPTION
**Pull request by VioletaScvortova**
Hi, Ivan. Below is the screenshot of my homework 7, Lesson 22 - Reduce, forEach and Map methods. 
The last task №4 was a bit difficult, and I finished it after we discussed this task during the Lesson 23.

JS_ Homework 7

### CODE REVIEW

**Comment by VioletaScvortova** [comment]
@IvanCeban I also have a question: 
do the Prettier and Beautify code editors format and structure the code correctly (parenthesis placement)?

Or both options can be used, for example:

const studentGrades = [
  { name: "Anna", note: 9 },
  { name: "Denis", note: 7 },
  { name: "Cristian", note: 8 },
  { name: "Daniel", note: 6 },
  { name: "Elena", note: 10 }
];

image

**Comment by IvanCeban** [comment]
Both options can be used. They are both of valid JS syntax. 
Prettier can edit them depending on it's configuration.

**Review by IvanCeban — APPROVED** [review]
Very good

**Comment by VioletaScvortova** [comment]
> Both options can be used. They are both of valid JS syntax. Prettier can edit them depending on it's configuration.

Got it. Thank you for the explanation!

**Pull request merged**
