### PR TITLE
Homework KMarketer project. Node.js and NPM

### PR DESCRIPTION
**Pull request by VioletaScvortova**
Hello, Ivan! Below is a screenshot of my homework. I followed the steps that you indicated and added my KMarketer project to http://localhost:1234

JS_ Homework 14

### CODE REVIEW

**Comment by Ivan-Ceban** [comment]
Well done! I see you've added node_modules in gitignore, but only after you pushed them. And now we have this in your PR:
image

which is insane :)

Please remove the nodemodules from gitignore. Commit changes. After that remove the folder node_modules. Commist changes. And again add it in gitignore and again commit changes. In this way you will get rid of it. 

Also I don't see your package.json file in the PR

**Comment by VioletaScvortova** [comment]
@Ivan-Ceban thank you a lot for your comments, please check it now.
Yes, I think I used the command "git add ." before I added node_modules to gitignore((

I tried to delete node_modules folder, but a couple of files in the folder and the folder itself still remained. Please advise me, what will be better to do with it - to remove the folder node_modules locally (not through VS) or something else?

image


package.json and package-lock.json were loaded in the first PR:

image

**Review by Ivan-Ceban — APPROVED** [review]
Well done, but please before merging remove the rest of the node_modules that are still in your PR

**Comment by VioletaScvortova** [comment]
> Well done, but please before merging remove the rest of the node_modules that are still in your PR

Thank you - done!

**Pull request merged**
